name: Build Container

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: image-builder
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: 'cloudopsmfzqb55r.azurecr.io'
          username: '${{ vars.ARM_CLIENT_ID }}' # IT-Dev-RunnerImageBuilder
          password: '${{ secrets.ARM_CLIENT_SECRET }}'
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.Ubuntu2004
          push: true
          tags: johnknutsonhc/ci-ubuntu:20.04
